### ISSUE TITLE
Use time.Now().Format(time.RFC3339) instead of time.Now().String() in "lastalive" messages

### ISSUE THREAD

**Issue by gtfierro** [immesys/bw2bind#10]
By default the `.String()` method can leave some annotation of monotonic time at the end, which complicates parsing. It would be much easier to parse and use the liveness messages in `service.go` if they used a standard format

https://github.com/immesys/bw2bind/blob/master/service.go#L136

https://github.com/immesys/bw2bind/blob/master/service.go#L49

It doesn't have to be RFC3339; any standard format would be great

**Comment by immesys** [comment]
yeah at the time that was written it was a fixed format. I'd merge a PR fixing that, otherwise I can fix it next week if reminded.

**Comment by gtfierro** [comment]
This issue was solved in https://github.com/immesys/bw2bind/pull/11
